# Generated by Django 5.0.6 on 2024-06-17 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allergenlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen', models.TextField(blank=True, null=True)),
                ('ingredientList', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'allergenlist',
            },
        ),
        migrations.CreateModel(
            name='stateNames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('states', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stateNames',
            },
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('ingredient', models.TextField(blank=True, null=True)),
                ('diet', models.TextField(blank=True, null=True)),
                ('flavour', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('likes', models.ManyToManyField(related_name='blogpost_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
